name = "gamelist"
main = "worker.js"
compatibility_date = "2026-06-10"
workers_dev = true

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "GAMELIST"
id = "e09b01c417e4454594500b70978f2521"
